# Setup to start installing the splash screen ( library - https://pub.dev/packages/flutter_native_splash )
# Command: `flutter pub run flutter_native_splash:create`
flutter_native_splash:
  color: "#1c1d1f"
  image: assets/images/splash_screen/main.png
  android_12:
    color: "#1c1d1f"
    icon_background_color: "#1c1d1f"
    image: assets/images/splash_screen/android_12.png
